// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomMenu.proto

package com.lvl6.proto;

public final class CustomMenusProto {
  private CustomMenusProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CustomMenuProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lvl6.proto.CustomMenuProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 customMenuId = 1;</code>
     */
    boolean hasCustomMenuId();
    /**
     * <code>optional int32 customMenuId = 1;</code>
     */
    int getCustomMenuId();

    /**
     * <code>optional int32 positionX = 2;</code>
     */
    boolean hasPositionX();
    /**
     * <code>optional int32 positionX = 2;</code>
     */
    int getPositionX();

    /**
     * <code>optional int32 positionY = 3;</code>
     */
    boolean hasPositionY();
    /**
     * <code>optional int32 positionY = 3;</code>
     */
    int getPositionY();

    /**
     * <code>optional int32 positionZ = 4;</code>
     */
    boolean hasPositionZ();
    /**
     * <code>optional int32 positionZ = 4;</code>
     */
    int getPositionZ();

    /**
     * <code>optional bool isJiggle = 5;</code>
     */
    boolean hasIsJiggle();
    /**
     * <code>optional bool isJiggle = 5;</code>
     */
    boolean getIsJiggle();

    /**
     * <code>optional string imageName = 6;</code>
     */
    boolean hasImageName();
    /**
     * <code>optional string imageName = 6;</code>
     */
    java.lang.String getImageName();
    /**
     * <code>optional string imageName = 6;</code>
     */
    com.google.protobuf.ByteString
        getImageNameBytes();

    /**
     * <code>optional int32 ipadPositionX = 7;</code>
     */
    boolean hasIpadPositionX();
    /**
     * <code>optional int32 ipadPositionX = 7;</code>
     */
    int getIpadPositionX();

    /**
     * <code>optional int32 ipadPositionY = 8;</code>
     */
    boolean hasIpadPositionY();
    /**
     * <code>optional int32 ipadPositionY = 8;</code>
     */
    int getIpadPositionY();
  }
  /**
   * Protobuf type {@code com.lvl6.proto.CustomMenuProto}
   */
  public static final class CustomMenuProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.lvl6.proto.CustomMenuProto)
      CustomMenuProtoOrBuilder {
    // Use CustomMenuProto.newBuilder() to construct.
    private CustomMenuProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CustomMenuProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CustomMenuProto defaultInstance;
    public static CustomMenuProto getDefaultInstance() {
      return defaultInstance;
    }

    public CustomMenuProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CustomMenuProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              customMenuId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              positionX_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              positionY_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              positionZ_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              isJiggle_ = input.readBool();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              imageName_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              ipadPositionX_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              ipadPositionY_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.proto.CustomMenusProto.internal_static_com_lvl6_proto_CustomMenuProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.proto.CustomMenusProto.internal_static_com_lvl6_proto_CustomMenuProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lvl6.proto.CustomMenusProto.CustomMenuProto.class, com.lvl6.proto.CustomMenusProto.CustomMenuProto.Builder.class);
    }

    public static com.google.protobuf.Parser<CustomMenuProto> PARSER =
        new com.google.protobuf.AbstractParser<CustomMenuProto>() {
      public CustomMenuProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomMenuProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CustomMenuProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CUSTOMMENUID_FIELD_NUMBER = 1;
    private int customMenuId_;
    /**
     * <code>optional int32 customMenuId = 1;</code>
     */
    public boolean hasCustomMenuId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 customMenuId = 1;</code>
     */
    public int getCustomMenuId() {
      return customMenuId_;
    }

    public static final int POSITIONX_FIELD_NUMBER = 2;
    private int positionX_;
    /**
     * <code>optional int32 positionX = 2;</code>
     */
    public boolean hasPositionX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 positionX = 2;</code>
     */
    public int getPositionX() {
      return positionX_;
    }

    public static final int POSITIONY_FIELD_NUMBER = 3;
    private int positionY_;
    /**
     * <code>optional int32 positionY = 3;</code>
     */
    public boolean hasPositionY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 positionY = 3;</code>
     */
    public int getPositionY() {
      return positionY_;
    }

    public static final int POSITIONZ_FIELD_NUMBER = 4;
    private int positionZ_;
    /**
     * <code>optional int32 positionZ = 4;</code>
     */
    public boolean hasPositionZ() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 positionZ = 4;</code>
     */
    public int getPositionZ() {
      return positionZ_;
    }

    public static final int ISJIGGLE_FIELD_NUMBER = 5;
    private boolean isJiggle_;
    /**
     * <code>optional bool isJiggle = 5;</code>
     */
    public boolean hasIsJiggle() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool isJiggle = 5;</code>
     */
    public boolean getIsJiggle() {
      return isJiggle_;
    }

    public static final int IMAGENAME_FIELD_NUMBER = 6;
    private java.lang.Object imageName_;
    /**
     * <code>optional string imageName = 6;</code>
     */
    public boolean hasImageName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string imageName = 6;</code>
     */
    public java.lang.String getImageName() {
      java.lang.Object ref = imageName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          imageName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string imageName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getImageNameBytes() {
      java.lang.Object ref = imageName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IPADPOSITIONX_FIELD_NUMBER = 7;
    private int ipadPositionX_;
    /**
     * <code>optional int32 ipadPositionX = 7;</code>
     */
    public boolean hasIpadPositionX() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 ipadPositionX = 7;</code>
     */
    public int getIpadPositionX() {
      return ipadPositionX_;
    }

    public static final int IPADPOSITIONY_FIELD_NUMBER = 8;
    private int ipadPositionY_;
    /**
     * <code>optional int32 ipadPositionY = 8;</code>
     */
    public boolean hasIpadPositionY() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 ipadPositionY = 8;</code>
     */
    public int getIpadPositionY() {
      return ipadPositionY_;
    }

    private void initFields() {
      customMenuId_ = 0;
      positionX_ = 0;
      positionY_ = 0;
      positionZ_ = 0;
      isJiggle_ = false;
      imageName_ = "";
      ipadPositionX_ = 0;
      ipadPositionY_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, customMenuId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, positionX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, positionY_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, positionZ_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, isJiggle_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getImageNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, ipadPositionX_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, ipadPositionY_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, customMenuId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, positionX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, positionY_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, positionZ_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isJiggle_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getImageNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, ipadPositionX_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, ipadPositionY_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lvl6.proto.CustomMenusProto.CustomMenuProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lvl6.proto.CustomMenusProto.CustomMenuProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lvl6.proto.CustomMenusProto.CustomMenuProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lvl6.proto.CustomMenusProto.CustomMenuProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lvl6.proto.CustomMenusProto.CustomMenuProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lvl6.proto.CustomMenusProto.CustomMenuProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lvl6.proto.CustomMenusProto.CustomMenuProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lvl6.proto.CustomMenusProto.CustomMenuProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lvl6.proto.CustomMenusProto.CustomMenuProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lvl6.proto.CustomMenusProto.CustomMenuProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.proto.CustomMenusProto.CustomMenuProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lvl6.proto.CustomMenuProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lvl6.proto.CustomMenuProto)
        com.lvl6.proto.CustomMenusProto.CustomMenuProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.proto.CustomMenusProto.internal_static_com_lvl6_proto_CustomMenuProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.proto.CustomMenusProto.internal_static_com_lvl6_proto_CustomMenuProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lvl6.proto.CustomMenusProto.CustomMenuProto.class, com.lvl6.proto.CustomMenusProto.CustomMenuProto.Builder.class);
      }

      // Construct using com.lvl6.proto.CustomMenusProto.CustomMenuProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        customMenuId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        positionX_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        positionY_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        positionZ_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        isJiggle_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        imageName_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        ipadPositionX_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        ipadPositionY_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.proto.CustomMenusProto.internal_static_com_lvl6_proto_CustomMenuProto_descriptor;
      }

      public com.lvl6.proto.CustomMenusProto.CustomMenuProto getDefaultInstanceForType() {
        return com.lvl6.proto.CustomMenusProto.CustomMenuProto.getDefaultInstance();
      }

      public com.lvl6.proto.CustomMenusProto.CustomMenuProto build() {
        com.lvl6.proto.CustomMenusProto.CustomMenuProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lvl6.proto.CustomMenusProto.CustomMenuProto buildPartial() {
        com.lvl6.proto.CustomMenusProto.CustomMenuProto result = new com.lvl6.proto.CustomMenusProto.CustomMenuProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.customMenuId_ = customMenuId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.positionX_ = positionX_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.positionY_ = positionY_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.positionZ_ = positionZ_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.isJiggle_ = isJiggle_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.imageName_ = imageName_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.ipadPositionX_ = ipadPositionX_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.ipadPositionY_ = ipadPositionY_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.proto.CustomMenusProto.CustomMenuProto) {
          return mergeFrom((com.lvl6.proto.CustomMenusProto.CustomMenuProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lvl6.proto.CustomMenusProto.CustomMenuProto other) {
        if (other == com.lvl6.proto.CustomMenusProto.CustomMenuProto.getDefaultInstance()) return this;
        if (other.hasCustomMenuId()) {
          setCustomMenuId(other.getCustomMenuId());
        }
        if (other.hasPositionX()) {
          setPositionX(other.getPositionX());
        }
        if (other.hasPositionY()) {
          setPositionY(other.getPositionY());
        }
        if (other.hasPositionZ()) {
          setPositionZ(other.getPositionZ());
        }
        if (other.hasIsJiggle()) {
          setIsJiggle(other.getIsJiggle());
        }
        if (other.hasImageName()) {
          bitField0_ |= 0x00000020;
          imageName_ = other.imageName_;
          onChanged();
        }
        if (other.hasIpadPositionX()) {
          setIpadPositionX(other.getIpadPositionX());
        }
        if (other.hasIpadPositionY()) {
          setIpadPositionY(other.getIpadPositionY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lvl6.proto.CustomMenusProto.CustomMenuProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lvl6.proto.CustomMenusProto.CustomMenuProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int customMenuId_ ;
      /**
       * <code>optional int32 customMenuId = 1;</code>
       */
      public boolean hasCustomMenuId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 customMenuId = 1;</code>
       */
      public int getCustomMenuId() {
        return customMenuId_;
      }
      /**
       * <code>optional int32 customMenuId = 1;</code>
       */
      public Builder setCustomMenuId(int value) {
        bitField0_ |= 0x00000001;
        customMenuId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 customMenuId = 1;</code>
       */
      public Builder clearCustomMenuId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        customMenuId_ = 0;
        onChanged();
        return this;
      }

      private int positionX_ ;
      /**
       * <code>optional int32 positionX = 2;</code>
       */
      public boolean hasPositionX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 positionX = 2;</code>
       */
      public int getPositionX() {
        return positionX_;
      }
      /**
       * <code>optional int32 positionX = 2;</code>
       */
      public Builder setPositionX(int value) {
        bitField0_ |= 0x00000002;
        positionX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 positionX = 2;</code>
       */
      public Builder clearPositionX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        positionX_ = 0;
        onChanged();
        return this;
      }

      private int positionY_ ;
      /**
       * <code>optional int32 positionY = 3;</code>
       */
      public boolean hasPositionY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 positionY = 3;</code>
       */
      public int getPositionY() {
        return positionY_;
      }
      /**
       * <code>optional int32 positionY = 3;</code>
       */
      public Builder setPositionY(int value) {
        bitField0_ |= 0x00000004;
        positionY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 positionY = 3;</code>
       */
      public Builder clearPositionY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        positionY_ = 0;
        onChanged();
        return this;
      }

      private int positionZ_ ;
      /**
       * <code>optional int32 positionZ = 4;</code>
       */
      public boolean hasPositionZ() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 positionZ = 4;</code>
       */
      public int getPositionZ() {
        return positionZ_;
      }
      /**
       * <code>optional int32 positionZ = 4;</code>
       */
      public Builder setPositionZ(int value) {
        bitField0_ |= 0x00000008;
        positionZ_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 positionZ = 4;</code>
       */
      public Builder clearPositionZ() {
        bitField0_ = (bitField0_ & ~0x00000008);
        positionZ_ = 0;
        onChanged();
        return this;
      }

      private boolean isJiggle_ ;
      /**
       * <code>optional bool isJiggle = 5;</code>
       */
      public boolean hasIsJiggle() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool isJiggle = 5;</code>
       */
      public boolean getIsJiggle() {
        return isJiggle_;
      }
      /**
       * <code>optional bool isJiggle = 5;</code>
       */
      public Builder setIsJiggle(boolean value) {
        bitField0_ |= 0x00000010;
        isJiggle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isJiggle = 5;</code>
       */
      public Builder clearIsJiggle() {
        bitField0_ = (bitField0_ & ~0x00000010);
        isJiggle_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object imageName_ = "";
      /**
       * <code>optional string imageName = 6;</code>
       */
      public boolean hasImageName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string imageName = 6;</code>
       */
      public java.lang.String getImageName() {
        java.lang.Object ref = imageName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            imageName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string imageName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getImageNameBytes() {
        java.lang.Object ref = imageName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imageName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string imageName = 6;</code>
       */
      public Builder setImageName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        imageName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string imageName = 6;</code>
       */
      public Builder clearImageName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        imageName_ = getDefaultInstance().getImageName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string imageName = 6;</code>
       */
      public Builder setImageNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        imageName_ = value;
        onChanged();
        return this;
      }

      private int ipadPositionX_ ;
      /**
       * <code>optional int32 ipadPositionX = 7;</code>
       */
      public boolean hasIpadPositionX() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 ipadPositionX = 7;</code>
       */
      public int getIpadPositionX() {
        return ipadPositionX_;
      }
      /**
       * <code>optional int32 ipadPositionX = 7;</code>
       */
      public Builder setIpadPositionX(int value) {
        bitField0_ |= 0x00000040;
        ipadPositionX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ipadPositionX = 7;</code>
       */
      public Builder clearIpadPositionX() {
        bitField0_ = (bitField0_ & ~0x00000040);
        ipadPositionX_ = 0;
        onChanged();
        return this;
      }

      private int ipadPositionY_ ;
      /**
       * <code>optional int32 ipadPositionY = 8;</code>
       */
      public boolean hasIpadPositionY() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 ipadPositionY = 8;</code>
       */
      public int getIpadPositionY() {
        return ipadPositionY_;
      }
      /**
       * <code>optional int32 ipadPositionY = 8;</code>
       */
      public Builder setIpadPositionY(int value) {
        bitField0_ |= 0x00000080;
        ipadPositionY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ipadPositionY = 8;</code>
       */
      public Builder clearIpadPositionY() {
        bitField0_ = (bitField0_ & ~0x00000080);
        ipadPositionY_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.lvl6.proto.CustomMenuProto)
    }

    static {
      defaultInstance = new CustomMenuProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.lvl6.proto.CustomMenuProto)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lvl6_proto_CustomMenuProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lvl6_proto_CustomMenuProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020CustomMenu.proto\022\016com.lvl6.proto\"\263\001\n\017C" +
      "ustomMenuProto\022\024\n\014customMenuId\030\001 \001(\005\022\021\n\t" +
      "positionX\030\002 \001(\005\022\021\n\tpositionY\030\003 \001(\005\022\021\n\tpo" +
      "sitionZ\030\004 \001(\005\022\020\n\010isJiggle\030\005 \001(\010\022\021\n\timage" +
      "Name\030\006 \001(\t\022\025\n\ripadPositionX\030\007 \001(\005\022\025\n\ripa" +
      "dPositionY\030\010 \001(\005B\022B\020CustomMenusProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_lvl6_proto_CustomMenuProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lvl6_proto_CustomMenuProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_lvl6_proto_CustomMenuProto_descriptor,
        new java.lang.String[] { "CustomMenuId", "PositionX", "PositionY", "PositionZ", "IsJiggle", "ImageName", "IpadPositionX", "IpadPositionY", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
