// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventLeaderBoard.proto

package com.lvl6.proto;

public final class EventLeaderBoardProto {
  private EventLeaderBoardProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RetrieveStrengthLeaderBoardRequestProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lvl6.proto.RetrieveStrengthLeaderBoardRequestProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    boolean hasSender();
    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    com.lvl6.proto.UserProto.MinimumUserProto getSender();
    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder getSenderOrBuilder();

    /**
     * <code>optional int32 minRank = 2;</code>
     *
     * <pre>
     *for client: if you want the highest strength up to the 50th highest 
     *strength, minRank is 1, maxRank is 50
     *for server: ranks start at 0, offset client values
     * </pre>
     */
    boolean hasMinRank();
    /**
     * <code>optional int32 minRank = 2;</code>
     *
     * <pre>
     *for client: if you want the highest strength up to the 50th highest 
     *strength, minRank is 1, maxRank is 50
     *for server: ranks start at 0, offset client values
     * </pre>
     */
    int getMinRank();

    /**
     * <code>optional int32 maxRank = 3;</code>
     */
    boolean hasMaxRank();
    /**
     * <code>optional int32 maxRank = 3;</code>
     */
    int getMaxRank();
  }
  /**
   * Protobuf type {@code com.lvl6.proto.RetrieveStrengthLeaderBoardRequestProto}
   */
  public static final class RetrieveStrengthLeaderBoardRequestProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.lvl6.proto.RetrieveStrengthLeaderBoardRequestProto)
      RetrieveStrengthLeaderBoardRequestProtoOrBuilder {
    // Use RetrieveStrengthLeaderBoardRequestProto.newBuilder() to construct.
    private RetrieveStrengthLeaderBoardRequestProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RetrieveStrengthLeaderBoardRequestProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RetrieveStrengthLeaderBoardRequestProto defaultInstance;
    public static RetrieveStrengthLeaderBoardRequestProto getDefaultInstance() {
      return defaultInstance;
    }

    public RetrieveStrengthLeaderBoardRequestProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RetrieveStrengthLeaderBoardRequestProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.lvl6.proto.UserProto.MinimumUserProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = sender_.toBuilder();
              }
              sender_ = input.readMessage(com.lvl6.proto.UserProto.MinimumUserProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sender_);
                sender_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              minRank_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              maxRank_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.proto.EventLeaderBoardProto.internal_static_com_lvl6_proto_RetrieveStrengthLeaderBoardRequestProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.proto.EventLeaderBoardProto.internal_static_com_lvl6_proto_RetrieveStrengthLeaderBoardRequestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto.class, com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto.Builder.class);
    }

    public static com.google.protobuf.Parser<RetrieveStrengthLeaderBoardRequestProto> PARSER =
        new com.google.protobuf.AbstractParser<RetrieveStrengthLeaderBoardRequestProto>() {
      public RetrieveStrengthLeaderBoardRequestProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RetrieveStrengthLeaderBoardRequestProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RetrieveStrengthLeaderBoardRequestProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SENDER_FIELD_NUMBER = 1;
    private com.lvl6.proto.UserProto.MinimumUserProto sender_;
    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    public com.lvl6.proto.UserProto.MinimumUserProto getSender() {
      return sender_;
    }
    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    public com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder getSenderOrBuilder() {
      return sender_;
    }

    public static final int MINRANK_FIELD_NUMBER = 2;
    private int minRank_;
    /**
     * <code>optional int32 minRank = 2;</code>
     *
     * <pre>
     *for client: if you want the highest strength up to the 50th highest 
     *strength, minRank is 1, maxRank is 50
     *for server: ranks start at 0, offset client values
     * </pre>
     */
    public boolean hasMinRank() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 minRank = 2;</code>
     *
     * <pre>
     *for client: if you want the highest strength up to the 50th highest 
     *strength, minRank is 1, maxRank is 50
     *for server: ranks start at 0, offset client values
     * </pre>
     */
    public int getMinRank() {
      return minRank_;
    }

    public static final int MAXRANK_FIELD_NUMBER = 3;
    private int maxRank_;
    /**
     * <code>optional int32 maxRank = 3;</code>
     */
    public boolean hasMaxRank() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 maxRank = 3;</code>
     */
    public int getMaxRank() {
      return maxRank_;
    }

    private void initFields() {
      sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
      minRank_ = 0;
      maxRank_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, minRank_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, maxRank_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, minRank_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, maxRank_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lvl6.proto.RetrieveStrengthLeaderBoardRequestProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lvl6.proto.RetrieveStrengthLeaderBoardRequestProto)
        com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.proto.EventLeaderBoardProto.internal_static_com_lvl6_proto_RetrieveStrengthLeaderBoardRequestProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.proto.EventLeaderBoardProto.internal_static_com_lvl6_proto_RetrieveStrengthLeaderBoardRequestProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto.class, com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto.Builder.class);
      }

      // Construct using com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSenderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (senderBuilder_ == null) {
          sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        minRank_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        maxRank_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.proto.EventLeaderBoardProto.internal_static_com_lvl6_proto_RetrieveStrengthLeaderBoardRequestProto_descriptor;
      }

      public com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto getDefaultInstanceForType() {
        return com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto.getDefaultInstance();
      }

      public com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto build() {
        com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto buildPartial() {
        com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto result = new com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (senderBuilder_ == null) {
          result.sender_ = sender_;
        } else {
          result.sender_ = senderBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.minRank_ = minRank_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.maxRank_ = maxRank_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto) {
          return mergeFrom((com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto other) {
        if (other == com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto.getDefaultInstance()) return this;
        if (other.hasSender()) {
          mergeSender(other.getSender());
        }
        if (other.hasMinRank()) {
          setMinRank(other.getMinRank());
        }
        if (other.hasMaxRank()) {
          setMaxRank(other.getMaxRank());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardRequestProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.lvl6.proto.UserProto.MinimumUserProto sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.proto.UserProto.MinimumUserProto, com.lvl6.proto.UserProto.MinimumUserProto.Builder, com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder> senderBuilder_;
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public boolean hasSender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public com.lvl6.proto.UserProto.MinimumUserProto getSender() {
        if (senderBuilder_ == null) {
          return sender_;
        } else {
          return senderBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public Builder setSender(com.lvl6.proto.UserProto.MinimumUserProto value) {
        if (senderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sender_ = value;
          onChanged();
        } else {
          senderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public Builder setSender(
          com.lvl6.proto.UserProto.MinimumUserProto.Builder builderForValue) {
        if (senderBuilder_ == null) {
          sender_ = builderForValue.build();
          onChanged();
        } else {
          senderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public Builder mergeSender(com.lvl6.proto.UserProto.MinimumUserProto value) {
        if (senderBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              sender_ != com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance()) {
            sender_ =
              com.lvl6.proto.UserProto.MinimumUserProto.newBuilder(sender_).mergeFrom(value).buildPartial();
          } else {
            sender_ = value;
          }
          onChanged();
        } else {
          senderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public Builder clearSender() {
        if (senderBuilder_ == null) {
          sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
          onChanged();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public com.lvl6.proto.UserProto.MinimumUserProto.Builder getSenderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSenderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder getSenderOrBuilder() {
        if (senderBuilder_ != null) {
          return senderBuilder_.getMessageOrBuilder();
        } else {
          return sender_;
        }
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.proto.UserProto.MinimumUserProto, com.lvl6.proto.UserProto.MinimumUserProto.Builder, com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder> 
          getSenderFieldBuilder() {
        if (senderBuilder_ == null) {
          senderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.proto.UserProto.MinimumUserProto, com.lvl6.proto.UserProto.MinimumUserProto.Builder, com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder>(
                  getSender(),
                  getParentForChildren(),
                  isClean());
          sender_ = null;
        }
        return senderBuilder_;
      }

      private int minRank_ ;
      /**
       * <code>optional int32 minRank = 2;</code>
       *
       * <pre>
       *for client: if you want the highest strength up to the 50th highest 
       *strength, minRank is 1, maxRank is 50
       *for server: ranks start at 0, offset client values
       * </pre>
       */
      public boolean hasMinRank() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 minRank = 2;</code>
       *
       * <pre>
       *for client: if you want the highest strength up to the 50th highest 
       *strength, minRank is 1, maxRank is 50
       *for server: ranks start at 0, offset client values
       * </pre>
       */
      public int getMinRank() {
        return minRank_;
      }
      /**
       * <code>optional int32 minRank = 2;</code>
       *
       * <pre>
       *for client: if you want the highest strength up to the 50th highest 
       *strength, minRank is 1, maxRank is 50
       *for server: ranks start at 0, offset client values
       * </pre>
       */
      public Builder setMinRank(int value) {
        bitField0_ |= 0x00000002;
        minRank_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 minRank = 2;</code>
       *
       * <pre>
       *for client: if you want the highest strength up to the 50th highest 
       *strength, minRank is 1, maxRank is 50
       *for server: ranks start at 0, offset client values
       * </pre>
       */
      public Builder clearMinRank() {
        bitField0_ = (bitField0_ & ~0x00000002);
        minRank_ = 0;
        onChanged();
        return this;
      }

      private int maxRank_ ;
      /**
       * <code>optional int32 maxRank = 3;</code>
       */
      public boolean hasMaxRank() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 maxRank = 3;</code>
       */
      public int getMaxRank() {
        return maxRank_;
      }
      /**
       * <code>optional int32 maxRank = 3;</code>
       */
      public Builder setMaxRank(int value) {
        bitField0_ |= 0x00000004;
        maxRank_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 maxRank = 3;</code>
       */
      public Builder clearMaxRank() {
        bitField0_ = (bitField0_ & ~0x00000004);
        maxRank_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.lvl6.proto.RetrieveStrengthLeaderBoardRequestProto)
    }

    static {
      defaultInstance = new RetrieveStrengthLeaderBoardRequestProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.lvl6.proto.RetrieveStrengthLeaderBoardRequestProto)
  }

  public interface RetrieveStrengthLeaderBoardResponseProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lvl6.proto.RetrieveStrengthLeaderBoardResponseProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    boolean hasSender();
    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    com.lvl6.proto.UserProto.MinimumUserProto getSender();
    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder getSenderOrBuilder();

    /**
     * <code>optional .com.lvl6.proto.StrengthLeaderBoardProto senderLeaderBoardInfo = 2;</code>
     */
    boolean hasSenderLeaderBoardInfo();
    /**
     * <code>optional .com.lvl6.proto.StrengthLeaderBoardProto senderLeaderBoardInfo = 2;</code>
     */
    com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto getSenderLeaderBoardInfo();
    /**
     * <code>optional .com.lvl6.proto.StrengthLeaderBoardProto senderLeaderBoardInfo = 2;</code>
     */
    com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProtoOrBuilder getSenderLeaderBoardInfoOrBuilder();

    /**
     * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
     */
    java.util.List<com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto> 
        getLeaderBoardInfoList();
    /**
     * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
     */
    com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto getLeaderBoardInfo(int index);
    /**
     * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
     */
    int getLeaderBoardInfoCount();
    /**
     * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
     */
    java.util.List<? extends com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProtoOrBuilder> 
        getLeaderBoardInfoOrBuilderList();
    /**
     * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
     */
    com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProtoOrBuilder getLeaderBoardInfoOrBuilder(
        int index);

    /**
     * <code>optional .com.lvl6.proto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus status = 4;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional .com.lvl6.proto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus status = 4;</code>
     */
    com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus getStatus();
  }
  /**
   * Protobuf type {@code com.lvl6.proto.RetrieveStrengthLeaderBoardResponseProto}
   */
  public static final class RetrieveStrengthLeaderBoardResponseProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.lvl6.proto.RetrieveStrengthLeaderBoardResponseProto)
      RetrieveStrengthLeaderBoardResponseProtoOrBuilder {
    // Use RetrieveStrengthLeaderBoardResponseProto.newBuilder() to construct.
    private RetrieveStrengthLeaderBoardResponseProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RetrieveStrengthLeaderBoardResponseProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RetrieveStrengthLeaderBoardResponseProto defaultInstance;
    public static RetrieveStrengthLeaderBoardResponseProto getDefaultInstance() {
      return defaultInstance;
    }

    public RetrieveStrengthLeaderBoardResponseProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RetrieveStrengthLeaderBoardResponseProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.lvl6.proto.UserProto.MinimumUserProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = sender_.toBuilder();
              }
              sender_ = input.readMessage(com.lvl6.proto.UserProto.MinimumUserProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sender_);
                sender_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = senderLeaderBoardInfo_.toBuilder();
              }
              senderLeaderBoardInfo_ = input.readMessage(com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(senderLeaderBoardInfo_);
                senderLeaderBoardInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                leaderBoardInfo_ = new java.util.ArrayList<com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto>();
                mutable_bitField0_ |= 0x00000004;
              }
              leaderBoardInfo_.add(input.readMessage(com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.PARSER, extensionRegistry));
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus value = com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                status_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          leaderBoardInfo_ = java.util.Collections.unmodifiableList(leaderBoardInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.proto.EventLeaderBoardProto.internal_static_com_lvl6_proto_RetrieveStrengthLeaderBoardResponseProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.proto.EventLeaderBoardProto.internal_static_com_lvl6_proto_RetrieveStrengthLeaderBoardResponseProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto.class, com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto.Builder.class);
    }

    public static com.google.protobuf.Parser<RetrieveStrengthLeaderBoardResponseProto> PARSER =
        new com.google.protobuf.AbstractParser<RetrieveStrengthLeaderBoardResponseProto>() {
      public RetrieveStrengthLeaderBoardResponseProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RetrieveStrengthLeaderBoardResponseProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RetrieveStrengthLeaderBoardResponseProto> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.lvl6.proto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus}
     */
    public enum RetrieveStrengthLeaderBoardStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCESS = 1;</code>
       */
      SUCCESS(0, 1),
      /**
       * <code>FAIL_OTHER = 2;</code>
       */
      FAIL_OTHER(1, 2),
      /**
       * <code>FAIL_NO_RESULTS = 3;</code>
       */
      FAIL_NO_RESULTS(2, 3),
      ;

      /**
       * <code>SUCCESS = 1;</code>
       */
      public static final int SUCCESS_VALUE = 1;
      /**
       * <code>FAIL_OTHER = 2;</code>
       */
      public static final int FAIL_OTHER_VALUE = 2;
      /**
       * <code>FAIL_NO_RESULTS = 3;</code>
       */
      public static final int FAIL_NO_RESULTS_VALUE = 3;


      public final int getNumber() { return value; }

      public static RetrieveStrengthLeaderBoardStatus valueOf(int value) {
        switch (value) {
          case 1: return SUCCESS;
          case 2: return FAIL_OTHER;
          case 3: return FAIL_NO_RESULTS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RetrieveStrengthLeaderBoardStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<RetrieveStrengthLeaderBoardStatus>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RetrieveStrengthLeaderBoardStatus>() {
              public RetrieveStrengthLeaderBoardStatus findValueByNumber(int number) {
                return RetrieveStrengthLeaderBoardStatus.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto.getDescriptor().getEnumTypes().get(0);
      }

      private static final RetrieveStrengthLeaderBoardStatus[] VALUES = values();

      public static RetrieveStrengthLeaderBoardStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private RetrieveStrengthLeaderBoardStatus(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.lvl6.proto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus)
    }

    private int bitField0_;
    public static final int SENDER_FIELD_NUMBER = 1;
    private com.lvl6.proto.UserProto.MinimumUserProto sender_;
    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    public com.lvl6.proto.UserProto.MinimumUserProto getSender() {
      return sender_;
    }
    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    public com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder getSenderOrBuilder() {
      return sender_;
    }

    public static final int SENDERLEADERBOARDINFO_FIELD_NUMBER = 2;
    private com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto senderLeaderBoardInfo_;
    /**
     * <code>optional .com.lvl6.proto.StrengthLeaderBoardProto senderLeaderBoardInfo = 2;</code>
     */
    public boolean hasSenderLeaderBoardInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.lvl6.proto.StrengthLeaderBoardProto senderLeaderBoardInfo = 2;</code>
     */
    public com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto getSenderLeaderBoardInfo() {
      return senderLeaderBoardInfo_;
    }
    /**
     * <code>optional .com.lvl6.proto.StrengthLeaderBoardProto senderLeaderBoardInfo = 2;</code>
     */
    public com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProtoOrBuilder getSenderLeaderBoardInfoOrBuilder() {
      return senderLeaderBoardInfo_;
    }

    public static final int LEADERBOARDINFO_FIELD_NUMBER = 3;
    private java.util.List<com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto> leaderBoardInfo_;
    /**
     * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
     */
    public java.util.List<com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto> getLeaderBoardInfoList() {
      return leaderBoardInfo_;
    }
    /**
     * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
     */
    public java.util.List<? extends com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProtoOrBuilder> 
        getLeaderBoardInfoOrBuilderList() {
      return leaderBoardInfo_;
    }
    /**
     * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
     */
    public int getLeaderBoardInfoCount() {
      return leaderBoardInfo_.size();
    }
    /**
     * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
     */
    public com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto getLeaderBoardInfo(int index) {
      return leaderBoardInfo_.get(index);
    }
    /**
     * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
     */
    public com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProtoOrBuilder getLeaderBoardInfoOrBuilder(
        int index) {
      return leaderBoardInfo_.get(index);
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus status_;
    /**
     * <code>optional .com.lvl6.proto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus status = 4;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.lvl6.proto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus status = 4;</code>
     */
    public com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus getStatus() {
      return status_;
    }

    private void initFields() {
      sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
      senderLeaderBoardInfo_ = com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.getDefaultInstance();
      leaderBoardInfo_ = java.util.Collections.emptyList();
      status_ = com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus.SUCCESS;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, senderLeaderBoardInfo_);
      }
      for (int i = 0; i < leaderBoardInfo_.size(); i++) {
        output.writeMessage(3, leaderBoardInfo_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(4, status_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, senderLeaderBoardInfo_);
      }
      for (int i = 0; i < leaderBoardInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, leaderBoardInfo_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, status_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lvl6.proto.RetrieveStrengthLeaderBoardResponseProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lvl6.proto.RetrieveStrengthLeaderBoardResponseProto)
        com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.proto.EventLeaderBoardProto.internal_static_com_lvl6_proto_RetrieveStrengthLeaderBoardResponseProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.proto.EventLeaderBoardProto.internal_static_com_lvl6_proto_RetrieveStrengthLeaderBoardResponseProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto.class, com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto.Builder.class);
      }

      // Construct using com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSenderFieldBuilder();
          getSenderLeaderBoardInfoFieldBuilder();
          getLeaderBoardInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (senderBuilder_ == null) {
          sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (senderLeaderBoardInfoBuilder_ == null) {
          senderLeaderBoardInfo_ = com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.getDefaultInstance();
        } else {
          senderLeaderBoardInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (leaderBoardInfoBuilder_ == null) {
          leaderBoardInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          leaderBoardInfoBuilder_.clear();
        }
        status_ = com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.proto.EventLeaderBoardProto.internal_static_com_lvl6_proto_RetrieveStrengthLeaderBoardResponseProto_descriptor;
      }

      public com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto getDefaultInstanceForType() {
        return com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto.getDefaultInstance();
      }

      public com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto build() {
        com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto buildPartial() {
        com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto result = new com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (senderBuilder_ == null) {
          result.sender_ = sender_;
        } else {
          result.sender_ = senderBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (senderLeaderBoardInfoBuilder_ == null) {
          result.senderLeaderBoardInfo_ = senderLeaderBoardInfo_;
        } else {
          result.senderLeaderBoardInfo_ = senderLeaderBoardInfoBuilder_.build();
        }
        if (leaderBoardInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            leaderBoardInfo_ = java.util.Collections.unmodifiableList(leaderBoardInfo_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.leaderBoardInfo_ = leaderBoardInfo_;
        } else {
          result.leaderBoardInfo_ = leaderBoardInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto) {
          return mergeFrom((com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto other) {
        if (other == com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto.getDefaultInstance()) return this;
        if (other.hasSender()) {
          mergeSender(other.getSender());
        }
        if (other.hasSenderLeaderBoardInfo()) {
          mergeSenderLeaderBoardInfo(other.getSenderLeaderBoardInfo());
        }
        if (leaderBoardInfoBuilder_ == null) {
          if (!other.leaderBoardInfo_.isEmpty()) {
            if (leaderBoardInfo_.isEmpty()) {
              leaderBoardInfo_ = other.leaderBoardInfo_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureLeaderBoardInfoIsMutable();
              leaderBoardInfo_.addAll(other.leaderBoardInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.leaderBoardInfo_.isEmpty()) {
            if (leaderBoardInfoBuilder_.isEmpty()) {
              leaderBoardInfoBuilder_.dispose();
              leaderBoardInfoBuilder_ = null;
              leaderBoardInfo_ = other.leaderBoardInfo_;
              bitField0_ = (bitField0_ & ~0x00000004);
              leaderBoardInfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLeaderBoardInfoFieldBuilder() : null;
            } else {
              leaderBoardInfoBuilder_.addAllMessages(other.leaderBoardInfo_);
            }
          }
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.lvl6.proto.UserProto.MinimumUserProto sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.proto.UserProto.MinimumUserProto, com.lvl6.proto.UserProto.MinimumUserProto.Builder, com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder> senderBuilder_;
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public boolean hasSender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public com.lvl6.proto.UserProto.MinimumUserProto getSender() {
        if (senderBuilder_ == null) {
          return sender_;
        } else {
          return senderBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public Builder setSender(com.lvl6.proto.UserProto.MinimumUserProto value) {
        if (senderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sender_ = value;
          onChanged();
        } else {
          senderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public Builder setSender(
          com.lvl6.proto.UserProto.MinimumUserProto.Builder builderForValue) {
        if (senderBuilder_ == null) {
          sender_ = builderForValue.build();
          onChanged();
        } else {
          senderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public Builder mergeSender(com.lvl6.proto.UserProto.MinimumUserProto value) {
        if (senderBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              sender_ != com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance()) {
            sender_ =
              com.lvl6.proto.UserProto.MinimumUserProto.newBuilder(sender_).mergeFrom(value).buildPartial();
          } else {
            sender_ = value;
          }
          onChanged();
        } else {
          senderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public Builder clearSender() {
        if (senderBuilder_ == null) {
          sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
          onChanged();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public com.lvl6.proto.UserProto.MinimumUserProto.Builder getSenderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSenderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder getSenderOrBuilder() {
        if (senderBuilder_ != null) {
          return senderBuilder_.getMessageOrBuilder();
        } else {
          return sender_;
        }
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.proto.UserProto.MinimumUserProto, com.lvl6.proto.UserProto.MinimumUserProto.Builder, com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder> 
          getSenderFieldBuilder() {
        if (senderBuilder_ == null) {
          senderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.proto.UserProto.MinimumUserProto, com.lvl6.proto.UserProto.MinimumUserProto.Builder, com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder>(
                  getSender(),
                  getParentForChildren(),
                  isClean());
          sender_ = null;
        }
        return senderBuilder_;
      }

      private com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto senderLeaderBoardInfo_ = com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto, com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.Builder, com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProtoOrBuilder> senderLeaderBoardInfoBuilder_;
      /**
       * <code>optional .com.lvl6.proto.StrengthLeaderBoardProto senderLeaderBoardInfo = 2;</code>
       */
      public boolean hasSenderLeaderBoardInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.lvl6.proto.StrengthLeaderBoardProto senderLeaderBoardInfo = 2;</code>
       */
      public com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto getSenderLeaderBoardInfo() {
        if (senderLeaderBoardInfoBuilder_ == null) {
          return senderLeaderBoardInfo_;
        } else {
          return senderLeaderBoardInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.lvl6.proto.StrengthLeaderBoardProto senderLeaderBoardInfo = 2;</code>
       */
      public Builder setSenderLeaderBoardInfo(com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto value) {
        if (senderLeaderBoardInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          senderLeaderBoardInfo_ = value;
          onChanged();
        } else {
          senderLeaderBoardInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.StrengthLeaderBoardProto senderLeaderBoardInfo = 2;</code>
       */
      public Builder setSenderLeaderBoardInfo(
          com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.Builder builderForValue) {
        if (senderLeaderBoardInfoBuilder_ == null) {
          senderLeaderBoardInfo_ = builderForValue.build();
          onChanged();
        } else {
          senderLeaderBoardInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.StrengthLeaderBoardProto senderLeaderBoardInfo = 2;</code>
       */
      public Builder mergeSenderLeaderBoardInfo(com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto value) {
        if (senderLeaderBoardInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              senderLeaderBoardInfo_ != com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.getDefaultInstance()) {
            senderLeaderBoardInfo_ =
              com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.newBuilder(senderLeaderBoardInfo_).mergeFrom(value).buildPartial();
          } else {
            senderLeaderBoardInfo_ = value;
          }
          onChanged();
        } else {
          senderLeaderBoardInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.StrengthLeaderBoardProto senderLeaderBoardInfo = 2;</code>
       */
      public Builder clearSenderLeaderBoardInfo() {
        if (senderLeaderBoardInfoBuilder_ == null) {
          senderLeaderBoardInfo_ = com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.getDefaultInstance();
          onChanged();
        } else {
          senderLeaderBoardInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.StrengthLeaderBoardProto senderLeaderBoardInfo = 2;</code>
       */
      public com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.Builder getSenderLeaderBoardInfoBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getSenderLeaderBoardInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.lvl6.proto.StrengthLeaderBoardProto senderLeaderBoardInfo = 2;</code>
       */
      public com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProtoOrBuilder getSenderLeaderBoardInfoOrBuilder() {
        if (senderLeaderBoardInfoBuilder_ != null) {
          return senderLeaderBoardInfoBuilder_.getMessageOrBuilder();
        } else {
          return senderLeaderBoardInfo_;
        }
      }
      /**
       * <code>optional .com.lvl6.proto.StrengthLeaderBoardProto senderLeaderBoardInfo = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto, com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.Builder, com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProtoOrBuilder> 
          getSenderLeaderBoardInfoFieldBuilder() {
        if (senderLeaderBoardInfoBuilder_ == null) {
          senderLeaderBoardInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto, com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.Builder, com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProtoOrBuilder>(
                  getSenderLeaderBoardInfo(),
                  getParentForChildren(),
                  isClean());
          senderLeaderBoardInfo_ = null;
        }
        return senderLeaderBoardInfoBuilder_;
      }

      private java.util.List<com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto> leaderBoardInfo_ =
        java.util.Collections.emptyList();
      private void ensureLeaderBoardInfoIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          leaderBoardInfo_ = new java.util.ArrayList<com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto>(leaderBoardInfo_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto, com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.Builder, com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProtoOrBuilder> leaderBoardInfoBuilder_;

      /**
       * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
       */
      public java.util.List<com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto> getLeaderBoardInfoList() {
        if (leaderBoardInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(leaderBoardInfo_);
        } else {
          return leaderBoardInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
       */
      public int getLeaderBoardInfoCount() {
        if (leaderBoardInfoBuilder_ == null) {
          return leaderBoardInfo_.size();
        } else {
          return leaderBoardInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
       */
      public com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto getLeaderBoardInfo(int index) {
        if (leaderBoardInfoBuilder_ == null) {
          return leaderBoardInfo_.get(index);
        } else {
          return leaderBoardInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
       */
      public Builder setLeaderBoardInfo(
          int index, com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto value) {
        if (leaderBoardInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLeaderBoardInfoIsMutable();
          leaderBoardInfo_.set(index, value);
          onChanged();
        } else {
          leaderBoardInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
       */
      public Builder setLeaderBoardInfo(
          int index, com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.Builder builderForValue) {
        if (leaderBoardInfoBuilder_ == null) {
          ensureLeaderBoardInfoIsMutable();
          leaderBoardInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          leaderBoardInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
       */
      public Builder addLeaderBoardInfo(com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto value) {
        if (leaderBoardInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLeaderBoardInfoIsMutable();
          leaderBoardInfo_.add(value);
          onChanged();
        } else {
          leaderBoardInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
       */
      public Builder addLeaderBoardInfo(
          int index, com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto value) {
        if (leaderBoardInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLeaderBoardInfoIsMutable();
          leaderBoardInfo_.add(index, value);
          onChanged();
        } else {
          leaderBoardInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
       */
      public Builder addLeaderBoardInfo(
          com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.Builder builderForValue) {
        if (leaderBoardInfoBuilder_ == null) {
          ensureLeaderBoardInfoIsMutable();
          leaderBoardInfo_.add(builderForValue.build());
          onChanged();
        } else {
          leaderBoardInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
       */
      public Builder addLeaderBoardInfo(
          int index, com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.Builder builderForValue) {
        if (leaderBoardInfoBuilder_ == null) {
          ensureLeaderBoardInfoIsMutable();
          leaderBoardInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          leaderBoardInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
       */
      public Builder addAllLeaderBoardInfo(
          java.lang.Iterable<? extends com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto> values) {
        if (leaderBoardInfoBuilder_ == null) {
          ensureLeaderBoardInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, leaderBoardInfo_);
          onChanged();
        } else {
          leaderBoardInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
       */
      public Builder clearLeaderBoardInfo() {
        if (leaderBoardInfoBuilder_ == null) {
          leaderBoardInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          leaderBoardInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
       */
      public Builder removeLeaderBoardInfo(int index) {
        if (leaderBoardInfoBuilder_ == null) {
          ensureLeaderBoardInfoIsMutable();
          leaderBoardInfo_.remove(index);
          onChanged();
        } else {
          leaderBoardInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
       */
      public com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.Builder getLeaderBoardInfoBuilder(
          int index) {
        return getLeaderBoardInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
       */
      public com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProtoOrBuilder getLeaderBoardInfoOrBuilder(
          int index) {
        if (leaderBoardInfoBuilder_ == null) {
          return leaderBoardInfo_.get(index);  } else {
          return leaderBoardInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
       */
      public java.util.List<? extends com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProtoOrBuilder> 
           getLeaderBoardInfoOrBuilderList() {
        if (leaderBoardInfoBuilder_ != null) {
          return leaderBoardInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(leaderBoardInfo_);
        }
      }
      /**
       * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
       */
      public com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.Builder addLeaderBoardInfoBuilder() {
        return getLeaderBoardInfoFieldBuilder().addBuilder(
            com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.getDefaultInstance());
      }
      /**
       * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
       */
      public com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.Builder addLeaderBoardInfoBuilder(
          int index) {
        return getLeaderBoardInfoFieldBuilder().addBuilder(
            index, com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.getDefaultInstance());
      }
      /**
       * <code>repeated .com.lvl6.proto.StrengthLeaderBoardProto leaderBoardInfo = 3;</code>
       */
      public java.util.List<com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.Builder> 
           getLeaderBoardInfoBuilderList() {
        return getLeaderBoardInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto, com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.Builder, com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProtoOrBuilder> 
          getLeaderBoardInfoFieldBuilder() {
        if (leaderBoardInfoBuilder_ == null) {
          leaderBoardInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto, com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProto.Builder, com.lvl6.proto.LeaderBoardProto.StrengthLeaderBoardProtoOrBuilder>(
                  leaderBoardInfo_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          leaderBoardInfo_ = null;
        }
        return leaderBoardInfoBuilder_;
      }

      private com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus status_ = com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus.SUCCESS;
      /**
       * <code>optional .com.lvl6.proto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus status = 4;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .com.lvl6.proto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus status = 4;</code>
       */
      public com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus getStatus() {
        return status_;
      }
      /**
       * <code>optional .com.lvl6.proto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus status = 4;</code>
       */
      public Builder setStatus(com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus status = 4;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = com.lvl6.proto.EventLeaderBoardProto.RetrieveStrengthLeaderBoardResponseProto.RetrieveStrengthLeaderBoardStatus.SUCCESS;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.lvl6.proto.RetrieveStrengthLeaderBoardResponseProto)
    }

    static {
      defaultInstance = new RetrieveStrengthLeaderBoardResponseProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.lvl6.proto.RetrieveStrengthLeaderBoardResponseProto)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lvl6_proto_RetrieveStrengthLeaderBoardRequestProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lvl6_proto_RetrieveStrengthLeaderBoardRequestProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lvl6_proto_RetrieveStrengthLeaderBoardResponseProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lvl6_proto_RetrieveStrengthLeaderBoardResponseProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026EventLeaderBoard.proto\022\016com.lvl6.proto" +
      "\032\021LeaderBoard.proto\032\nUser.proto\"}\n\'Retri" +
      "eveStrengthLeaderBoardRequestProto\0220\n\006se" +
      "nder\030\001 \001(\0132 .com.lvl6.proto.MinimumUserP" +
      "roto\022\017\n\007minRank\030\002 \001(\005\022\017\n\007maxRank\030\003 \001(\005\"\253" +
      "\003\n(RetrieveStrengthLeaderBoardResponsePr" +
      "oto\0220\n\006sender\030\001 \001(\0132 .com.lvl6.proto.Min" +
      "imumUserProto\022G\n\025senderLeaderBoardInfo\030\002" +
      " \001(\0132(.com.lvl6.proto.StrengthLeaderBoar" +
      "dProto\022A\n\017leaderBoardInfo\030\003 \003(\0132(.com.lv",
      "l6.proto.StrengthLeaderBoardProto\022j\n\006sta" +
      "tus\030\004 \001(\0162Z.com.lvl6.proto.RetrieveStren" +
      "gthLeaderBoardResponseProto.RetrieveStre" +
      "ngthLeaderBoardStatus\"U\n!RetrieveStrengt" +
      "hLeaderBoardStatus\022\013\n\007SUCCESS\020\001\022\016\n\nFAIL_" +
      "OTHER\020\002\022\023\n\017FAIL_NO_RESULTS\020\003B\027B\025EventLea" +
      "derBoardProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lvl6.proto.LeaderBoardProto.getDescriptor(),
          com.lvl6.proto.UserProto.getDescriptor(),
        }, assigner);
    internal_static_com_lvl6_proto_RetrieveStrengthLeaderBoardRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lvl6_proto_RetrieveStrengthLeaderBoardRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_lvl6_proto_RetrieveStrengthLeaderBoardRequestProto_descriptor,
        new java.lang.String[] { "Sender", "MinRank", "MaxRank", });
    internal_static_com_lvl6_proto_RetrieveStrengthLeaderBoardResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_lvl6_proto_RetrieveStrengthLeaderBoardResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_lvl6_proto_RetrieveStrengthLeaderBoardResponseProto_descriptor,
        new java.lang.String[] { "Sender", "SenderLeaderBoardInfo", "LeaderBoardInfo", "Status", });
    com.lvl6.proto.LeaderBoardProto.getDescriptor();
    com.lvl6.proto.UserProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
