// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventApns.proto

package com.lvl6.proto;

public final class EventApnsProto {
  private EventApnsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EnableAPNSRequestProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lvl6.proto.EnableAPNSRequestProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    boolean hasSender();
    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    com.lvl6.proto.UserProto.MinimumUserProto getSender();
    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder getSenderOrBuilder();

    /**
     * <code>optional string deviceToken = 2;</code>
     */
    boolean hasDeviceToken();
    /**
     * <code>optional string deviceToken = 2;</code>
     */
    java.lang.String getDeviceToken();
    /**
     * <code>optional string deviceToken = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeviceTokenBytes();
  }
  /**
   * Protobuf type {@code com.lvl6.proto.EnableAPNSRequestProto}
   */
  public static final class EnableAPNSRequestProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.lvl6.proto.EnableAPNSRequestProto)
      EnableAPNSRequestProtoOrBuilder {
    // Use EnableAPNSRequestProto.newBuilder() to construct.
    private EnableAPNSRequestProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EnableAPNSRequestProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EnableAPNSRequestProto defaultInstance;
    public static EnableAPNSRequestProto getDefaultInstance() {
      return defaultInstance;
    }

    public EnableAPNSRequestProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EnableAPNSRequestProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.lvl6.proto.UserProto.MinimumUserProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = sender_.toBuilder();
              }
              sender_ = input.readMessage(com.lvl6.proto.UserProto.MinimumUserProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sender_);
                sender_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              deviceToken_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.proto.EventApnsProto.internal_static_com_lvl6_proto_EnableAPNSRequestProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.proto.EventApnsProto.internal_static_com_lvl6_proto_EnableAPNSRequestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto.class, com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto.Builder.class);
    }

    public static com.google.protobuf.Parser<EnableAPNSRequestProto> PARSER =
        new com.google.protobuf.AbstractParser<EnableAPNSRequestProto>() {
      public EnableAPNSRequestProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnableAPNSRequestProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EnableAPNSRequestProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SENDER_FIELD_NUMBER = 1;
    private com.lvl6.proto.UserProto.MinimumUserProto sender_;
    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    public com.lvl6.proto.UserProto.MinimumUserProto getSender() {
      return sender_;
    }
    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    public com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder getSenderOrBuilder() {
      return sender_;
    }

    public static final int DEVICETOKEN_FIELD_NUMBER = 2;
    private java.lang.Object deviceToken_;
    /**
     * <code>optional string deviceToken = 2;</code>
     */
    public boolean hasDeviceToken() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string deviceToken = 2;</code>
     */
    public java.lang.String getDeviceToken() {
      java.lang.Object ref = deviceToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceToken_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string deviceToken = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceTokenBytes() {
      java.lang.Object ref = deviceToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
      deviceToken_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDeviceTokenBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDeviceTokenBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lvl6.proto.EnableAPNSRequestProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lvl6.proto.EnableAPNSRequestProto)
        com.lvl6.proto.EventApnsProto.EnableAPNSRequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.proto.EventApnsProto.internal_static_com_lvl6_proto_EnableAPNSRequestProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.proto.EventApnsProto.internal_static_com_lvl6_proto_EnableAPNSRequestProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto.class, com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto.Builder.class);
      }

      // Construct using com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSenderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (senderBuilder_ == null) {
          sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.proto.EventApnsProto.internal_static_com_lvl6_proto_EnableAPNSRequestProto_descriptor;
      }

      public com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto getDefaultInstanceForType() {
        return com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto.getDefaultInstance();
      }

      public com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto build() {
        com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto buildPartial() {
        com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto result = new com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (senderBuilder_ == null) {
          result.sender_ = sender_;
        } else {
          result.sender_ = senderBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deviceToken_ = deviceToken_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto) {
          return mergeFrom((com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto other) {
        if (other == com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto.getDefaultInstance()) return this;
        if (other.hasSender()) {
          mergeSender(other.getSender());
        }
        if (other.hasDeviceToken()) {
          bitField0_ |= 0x00000002;
          deviceToken_ = other.deviceToken_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lvl6.proto.EventApnsProto.EnableAPNSRequestProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.lvl6.proto.UserProto.MinimumUserProto sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.proto.UserProto.MinimumUserProto, com.lvl6.proto.UserProto.MinimumUserProto.Builder, com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder> senderBuilder_;
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public boolean hasSender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public com.lvl6.proto.UserProto.MinimumUserProto getSender() {
        if (senderBuilder_ == null) {
          return sender_;
        } else {
          return senderBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public Builder setSender(com.lvl6.proto.UserProto.MinimumUserProto value) {
        if (senderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sender_ = value;
          onChanged();
        } else {
          senderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public Builder setSender(
          com.lvl6.proto.UserProto.MinimumUserProto.Builder builderForValue) {
        if (senderBuilder_ == null) {
          sender_ = builderForValue.build();
          onChanged();
        } else {
          senderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public Builder mergeSender(com.lvl6.proto.UserProto.MinimumUserProto value) {
        if (senderBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              sender_ != com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance()) {
            sender_ =
              com.lvl6.proto.UserProto.MinimumUserProto.newBuilder(sender_).mergeFrom(value).buildPartial();
          } else {
            sender_ = value;
          }
          onChanged();
        } else {
          senderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public Builder clearSender() {
        if (senderBuilder_ == null) {
          sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
          onChanged();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public com.lvl6.proto.UserProto.MinimumUserProto.Builder getSenderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSenderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder getSenderOrBuilder() {
        if (senderBuilder_ != null) {
          return senderBuilder_.getMessageOrBuilder();
        } else {
          return sender_;
        }
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.proto.UserProto.MinimumUserProto, com.lvl6.proto.UserProto.MinimumUserProto.Builder, com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder> 
          getSenderFieldBuilder() {
        if (senderBuilder_ == null) {
          senderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.proto.UserProto.MinimumUserProto, com.lvl6.proto.UserProto.MinimumUserProto.Builder, com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder>(
                  getSender(),
                  getParentForChildren(),
                  isClean());
          sender_ = null;
        }
        return senderBuilder_;
      }

      private java.lang.Object deviceToken_ = "";
      /**
       * <code>optional string deviceToken = 2;</code>
       */
      public boolean hasDeviceToken() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string deviceToken = 2;</code>
       */
      public java.lang.String getDeviceToken() {
        java.lang.Object ref = deviceToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceToken_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string deviceToken = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceTokenBytes() {
        java.lang.Object ref = deviceToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string deviceToken = 2;</code>
       */
      public Builder setDeviceToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceToken = 2;</code>
       */
      public Builder clearDeviceToken() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceToken_ = getDefaultInstance().getDeviceToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceToken = 2;</code>
       */
      public Builder setDeviceTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceToken_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.lvl6.proto.EnableAPNSRequestProto)
    }

    static {
      defaultInstance = new EnableAPNSRequestProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.lvl6.proto.EnableAPNSRequestProto)
  }

  public interface EnableAPNSResponseProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lvl6.proto.EnableAPNSResponseProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    boolean hasSender();
    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    com.lvl6.proto.UserProto.MinimumUserProto getSender();
    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder getSenderOrBuilder();

    /**
     * <code>optional .com.lvl6.proto.ResponseStatus status = 2;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional .com.lvl6.proto.ResponseStatus status = 2;</code>
     */
    com.lvl6.proto.SharedEnumConfigProto.ResponseStatus getStatus();
  }
  /**
   * Protobuf type {@code com.lvl6.proto.EnableAPNSResponseProto}
   *
   * <pre>
   *DONE
   * </pre>
   */
  public static final class EnableAPNSResponseProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.lvl6.proto.EnableAPNSResponseProto)
      EnableAPNSResponseProtoOrBuilder {
    // Use EnableAPNSResponseProto.newBuilder() to construct.
    private EnableAPNSResponseProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EnableAPNSResponseProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EnableAPNSResponseProto defaultInstance;
    public static EnableAPNSResponseProto getDefaultInstance() {
      return defaultInstance;
    }

    public EnableAPNSResponseProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EnableAPNSResponseProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.lvl6.proto.UserProto.MinimumUserProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = sender_.toBuilder();
              }
              sender_ = input.readMessage(com.lvl6.proto.UserProto.MinimumUserProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sender_);
                sender_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.lvl6.proto.SharedEnumConfigProto.ResponseStatus value = com.lvl6.proto.SharedEnumConfigProto.ResponseStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                status_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.proto.EventApnsProto.internal_static_com_lvl6_proto_EnableAPNSResponseProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.proto.EventApnsProto.internal_static_com_lvl6_proto_EnableAPNSResponseProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto.class, com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto.Builder.class);
    }

    public static com.google.protobuf.Parser<EnableAPNSResponseProto> PARSER =
        new com.google.protobuf.AbstractParser<EnableAPNSResponseProto>() {
      public EnableAPNSResponseProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnableAPNSResponseProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EnableAPNSResponseProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SENDER_FIELD_NUMBER = 1;
    private com.lvl6.proto.UserProto.MinimumUserProto sender_;
    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    public com.lvl6.proto.UserProto.MinimumUserProto getSender() {
      return sender_;
    }
    /**
     * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
     */
    public com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder getSenderOrBuilder() {
      return sender_;
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private com.lvl6.proto.SharedEnumConfigProto.ResponseStatus status_;
    /**
     * <code>optional .com.lvl6.proto.ResponseStatus status = 2;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.lvl6.proto.ResponseStatus status = 2;</code>
     */
    public com.lvl6.proto.SharedEnumConfigProto.ResponseStatus getStatus() {
      return status_;
    }

    private void initFields() {
      sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
      status_ = com.lvl6.proto.SharedEnumConfigProto.ResponseStatus.SUCCESS;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, status_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lvl6.proto.EnableAPNSResponseProto}
     *
     * <pre>
     *DONE
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lvl6.proto.EnableAPNSResponseProto)
        com.lvl6.proto.EventApnsProto.EnableAPNSResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.proto.EventApnsProto.internal_static_com_lvl6_proto_EnableAPNSResponseProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.proto.EventApnsProto.internal_static_com_lvl6_proto_EnableAPNSResponseProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto.class, com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto.Builder.class);
      }

      // Construct using com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSenderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (senderBuilder_ == null) {
          sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = com.lvl6.proto.SharedEnumConfigProto.ResponseStatus.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.proto.EventApnsProto.internal_static_com_lvl6_proto_EnableAPNSResponseProto_descriptor;
      }

      public com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto getDefaultInstanceForType() {
        return com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto.getDefaultInstance();
      }

      public com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto build() {
        com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto buildPartial() {
        com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto result = new com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (senderBuilder_ == null) {
          result.sender_ = sender_;
        } else {
          result.sender_ = senderBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto) {
          return mergeFrom((com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto other) {
        if (other == com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto.getDefaultInstance()) return this;
        if (other.hasSender()) {
          mergeSender(other.getSender());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lvl6.proto.EventApnsProto.EnableAPNSResponseProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.lvl6.proto.UserProto.MinimumUserProto sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.proto.UserProto.MinimumUserProto, com.lvl6.proto.UserProto.MinimumUserProto.Builder, com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder> senderBuilder_;
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public boolean hasSender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public com.lvl6.proto.UserProto.MinimumUserProto getSender() {
        if (senderBuilder_ == null) {
          return sender_;
        } else {
          return senderBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public Builder setSender(com.lvl6.proto.UserProto.MinimumUserProto value) {
        if (senderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sender_ = value;
          onChanged();
        } else {
          senderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public Builder setSender(
          com.lvl6.proto.UserProto.MinimumUserProto.Builder builderForValue) {
        if (senderBuilder_ == null) {
          sender_ = builderForValue.build();
          onChanged();
        } else {
          senderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public Builder mergeSender(com.lvl6.proto.UserProto.MinimumUserProto value) {
        if (senderBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              sender_ != com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance()) {
            sender_ =
              com.lvl6.proto.UserProto.MinimumUserProto.newBuilder(sender_).mergeFrom(value).buildPartial();
          } else {
            sender_ = value;
          }
          onChanged();
        } else {
          senderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public Builder clearSender() {
        if (senderBuilder_ == null) {
          sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
          onChanged();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public com.lvl6.proto.UserProto.MinimumUserProto.Builder getSenderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSenderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      public com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder getSenderOrBuilder() {
        if (senderBuilder_ != null) {
          return senderBuilder_.getMessageOrBuilder();
        } else {
          return sender_;
        }
      }
      /**
       * <code>optional .com.lvl6.proto.MinimumUserProto sender = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.proto.UserProto.MinimumUserProto, com.lvl6.proto.UserProto.MinimumUserProto.Builder, com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder> 
          getSenderFieldBuilder() {
        if (senderBuilder_ == null) {
          senderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.proto.UserProto.MinimumUserProto, com.lvl6.proto.UserProto.MinimumUserProto.Builder, com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder>(
                  getSender(),
                  getParentForChildren(),
                  isClean());
          sender_ = null;
        }
        return senderBuilder_;
      }

      private com.lvl6.proto.SharedEnumConfigProto.ResponseStatus status_ = com.lvl6.proto.SharedEnumConfigProto.ResponseStatus.SUCCESS;
      /**
       * <code>optional .com.lvl6.proto.ResponseStatus status = 2;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.lvl6.proto.ResponseStatus status = 2;</code>
       */
      public com.lvl6.proto.SharedEnumConfigProto.ResponseStatus getStatus() {
        return status_;
      }
      /**
       * <code>optional .com.lvl6.proto.ResponseStatus status = 2;</code>
       */
      public Builder setStatus(com.lvl6.proto.SharedEnumConfigProto.ResponseStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.lvl6.proto.ResponseStatus status = 2;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = com.lvl6.proto.SharedEnumConfigProto.ResponseStatus.SUCCESS;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.lvl6.proto.EnableAPNSResponseProto)
    }

    static {
      defaultInstance = new EnableAPNSResponseProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.lvl6.proto.EnableAPNSResponseProto)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lvl6_proto_EnableAPNSRequestProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lvl6_proto_EnableAPNSRequestProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lvl6_proto_EnableAPNSResponseProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lvl6_proto_EnableAPNSResponseProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017EventApns.proto\022\016com.lvl6.proto\032\026Share" +
      "dEnumConfig.proto\032\nUser.proto\"_\n\026EnableA" +
      "PNSRequestProto\0220\n\006sender\030\001 \001(\0132 .com.lv" +
      "l6.proto.MinimumUserProto\022\023\n\013deviceToken" +
      "\030\002 \001(\t\"{\n\027EnableAPNSResponseProto\0220\n\006sen" +
      "der\030\001 \001(\0132 .com.lvl6.proto.MinimumUserPr" +
      "oto\022.\n\006status\030\002 \001(\0162\036.com.lvl6.proto.Res" +
      "ponseStatusB\020B\016EventApnsProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lvl6.proto.SharedEnumConfigProto.getDescriptor(),
          com.lvl6.proto.UserProto.getDescriptor(),
        }, assigner);
    internal_static_com_lvl6_proto_EnableAPNSRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lvl6_proto_EnableAPNSRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_lvl6_proto_EnableAPNSRequestProto_descriptor,
        new java.lang.String[] { "Sender", "DeviceToken", });
    internal_static_com_lvl6_proto_EnableAPNSResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_lvl6_proto_EnableAPNSResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_lvl6_proto_EnableAPNSResponseProto_descriptor,
        new java.lang.String[] { "Sender", "Status", });
    com.lvl6.proto.SharedEnumConfigProto.getDescriptor();
    com.lvl6.proto.UserProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
