// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventDev.proto

package com.lvl6.proto;

public final class EventDevProto {
  private EventDevProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DevRequestProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .com.lvl6.proto.MinimumUserProto sender = 1;
    boolean hasSender();
    com.lvl6.proto.UserProto.MinimumUserProto getSender();
    com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder getSenderOrBuilder();
    
    // optional .com.lvl6.proto.DevRequest devRequest = 2;
    boolean hasDevRequest();
    com.lvl6.proto.DevProto.DevRequest getDevRequest();
    
    // optional int32 num = 3;
    boolean hasNum();
    int getNum();
  }
  public static final class DevRequestProto extends
      com.google.protobuf.GeneratedMessage
      implements DevRequestProtoOrBuilder {
    // Use DevRequestProto.newBuilder() to construct.
    private DevRequestProto(Builder builder) {
      super(builder);
    }
    private DevRequestProto(boolean noInit) {}
    
    private static final DevRequestProto defaultInstance;
    public static DevRequestProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public DevRequestProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.proto.EventDevProto.internal_static_com_lvl6_proto_DevRequestProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.proto.EventDevProto.internal_static_com_lvl6_proto_DevRequestProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .com.lvl6.proto.MinimumUserProto sender = 1;
    public static final int SENDER_FIELD_NUMBER = 1;
    private com.lvl6.proto.UserProto.MinimumUserProto sender_;
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.lvl6.proto.UserProto.MinimumUserProto getSender() {
      return sender_;
    }
    public com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder getSenderOrBuilder() {
      return sender_;
    }
    
    // optional .com.lvl6.proto.DevRequest devRequest = 2;
    public static final int DEVREQUEST_FIELD_NUMBER = 2;
    private com.lvl6.proto.DevProto.DevRequest devRequest_;
    public boolean hasDevRequest() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.lvl6.proto.DevProto.DevRequest getDevRequest() {
      return devRequest_;
    }
    
    // optional int32 num = 3;
    public static final int NUM_FIELD_NUMBER = 3;
    private int num_;
    public boolean hasNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getNum() {
      return num_;
    }
    
    private void initFields() {
      sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
      devRequest_ = com.lvl6.proto.DevProto.DevRequest.RESET_ACCOUNT;
      num_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, devRequest_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, num_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, devRequest_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, num_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.proto.EventDevProto.DevRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.EventDevProto.DevRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventDevProto.DevRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.EventDevProto.DevRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventDevProto.DevRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.EventDevProto.DevRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventDevProto.DevRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.EventDevProto.DevRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.EventDevProto.DevRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.EventDevProto.DevRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.proto.EventDevProto.DevRequestProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.proto.EventDevProto.DevRequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.proto.EventDevProto.internal_static_com_lvl6_proto_DevRequestProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.proto.EventDevProto.internal_static_com_lvl6_proto_DevRequestProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.proto.EventDevProto.DevRequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSenderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (senderBuilder_ == null) {
          sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        devRequest_ = com.lvl6.proto.DevProto.DevRequest.RESET_ACCOUNT;
        bitField0_ = (bitField0_ & ~0x00000002);
        num_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.proto.EventDevProto.DevRequestProto.getDescriptor();
      }
      
      public com.lvl6.proto.EventDevProto.DevRequestProto getDefaultInstanceForType() {
        return com.lvl6.proto.EventDevProto.DevRequestProto.getDefaultInstance();
      }
      
      public com.lvl6.proto.EventDevProto.DevRequestProto build() {
        com.lvl6.proto.EventDevProto.DevRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.proto.EventDevProto.DevRequestProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.proto.EventDevProto.DevRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.proto.EventDevProto.DevRequestProto buildPartial() {
        com.lvl6.proto.EventDevProto.DevRequestProto result = new com.lvl6.proto.EventDevProto.DevRequestProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (senderBuilder_ == null) {
          result.sender_ = sender_;
        } else {
          result.sender_ = senderBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.devRequest_ = devRequest_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.num_ = num_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.proto.EventDevProto.DevRequestProto) {
          return mergeFrom((com.lvl6.proto.EventDevProto.DevRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.proto.EventDevProto.DevRequestProto other) {
        if (other == com.lvl6.proto.EventDevProto.DevRequestProto.getDefaultInstance()) return this;
        if (other.hasSender()) {
          mergeSender(other.getSender());
        }
        if (other.hasDevRequest()) {
          setDevRequest(other.getDevRequest());
        }
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.lvl6.proto.UserProto.MinimumUserProto.Builder subBuilder = com.lvl6.proto.UserProto.MinimumUserProto.newBuilder();
              if (hasSender()) {
                subBuilder.mergeFrom(getSender());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSender(subBuilder.buildPartial());
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.lvl6.proto.DevProto.DevRequest value = com.lvl6.proto.DevProto.DevRequest.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                devRequest_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              num_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .com.lvl6.proto.MinimumUserProto sender = 1;
      private com.lvl6.proto.UserProto.MinimumUserProto sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.proto.UserProto.MinimumUserProto, com.lvl6.proto.UserProto.MinimumUserProto.Builder, com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder> senderBuilder_;
      public boolean hasSender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.lvl6.proto.UserProto.MinimumUserProto getSender() {
        if (senderBuilder_ == null) {
          return sender_;
        } else {
          return senderBuilder_.getMessage();
        }
      }
      public Builder setSender(com.lvl6.proto.UserProto.MinimumUserProto value) {
        if (senderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sender_ = value;
          onChanged();
        } else {
          senderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setSender(
          com.lvl6.proto.UserProto.MinimumUserProto.Builder builderForValue) {
        if (senderBuilder_ == null) {
          sender_ = builderForValue.build();
          onChanged();
        } else {
          senderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeSender(com.lvl6.proto.UserProto.MinimumUserProto value) {
        if (senderBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              sender_ != com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance()) {
            sender_ =
              com.lvl6.proto.UserProto.MinimumUserProto.newBuilder(sender_).mergeFrom(value).buildPartial();
          } else {
            sender_ = value;
          }
          onChanged();
        } else {
          senderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearSender() {
        if (senderBuilder_ == null) {
          sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
          onChanged();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.lvl6.proto.UserProto.MinimumUserProto.Builder getSenderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSenderFieldBuilder().getBuilder();
      }
      public com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder getSenderOrBuilder() {
        if (senderBuilder_ != null) {
          return senderBuilder_.getMessageOrBuilder();
        } else {
          return sender_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.proto.UserProto.MinimumUserProto, com.lvl6.proto.UserProto.MinimumUserProto.Builder, com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder> 
          getSenderFieldBuilder() {
        if (senderBuilder_ == null) {
          senderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.proto.UserProto.MinimumUserProto, com.lvl6.proto.UserProto.MinimumUserProto.Builder, com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder>(
                  sender_,
                  getParentForChildren(),
                  isClean());
          sender_ = null;
        }
        return senderBuilder_;
      }
      
      // optional .com.lvl6.proto.DevRequest devRequest = 2;
      private com.lvl6.proto.DevProto.DevRequest devRequest_ = com.lvl6.proto.DevProto.DevRequest.RESET_ACCOUNT;
      public boolean hasDevRequest() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.lvl6.proto.DevProto.DevRequest getDevRequest() {
        return devRequest_;
      }
      public Builder setDevRequest(com.lvl6.proto.DevProto.DevRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        devRequest_ = value;
        onChanged();
        return this;
      }
      public Builder clearDevRequest() {
        bitField0_ = (bitField0_ & ~0x00000002);
        devRequest_ = com.lvl6.proto.DevProto.DevRequest.RESET_ACCOUNT;
        onChanged();
        return this;
      }
      
      // optional int32 num = 3;
      private int num_ ;
      public boolean hasNum() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getNum() {
        return num_;
      }
      public Builder setNum(int value) {
        bitField0_ |= 0x00000004;
        num_ = value;
        onChanged();
        return this;
      }
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        num_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.lvl6.proto.DevRequestProto)
    }
    
    static {
      defaultInstance = new DevRequestProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.lvl6.proto.DevRequestProto)
  }
  
  public interface DevResponseProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .com.lvl6.proto.MinimumUserProto sender = 1;
    boolean hasSender();
    com.lvl6.proto.UserProto.MinimumUserProto getSender();
    com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder getSenderOrBuilder();
    
    // optional .com.lvl6.proto.DevResponseProto.DevStatus status = 2;
    boolean hasStatus();
    com.lvl6.proto.EventDevProto.DevResponseProto.DevStatus getStatus();
    
    // optional .com.lvl6.proto.FullUserMonsterProto fump = 3;
    boolean hasFump();
    com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto getFump();
    com.lvl6.proto.MonsterStuffProto.FullUserMonsterProtoOrBuilder getFumpOrBuilder();
  }
  public static final class DevResponseProto extends
      com.google.protobuf.GeneratedMessage
      implements DevResponseProtoOrBuilder {
    // Use DevResponseProto.newBuilder() to construct.
    private DevResponseProto(Builder builder) {
      super(builder);
    }
    private DevResponseProto(boolean noInit) {}
    
    private static final DevResponseProto defaultInstance;
    public static DevResponseProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public DevResponseProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.proto.EventDevProto.internal_static_com_lvl6_proto_DevResponseProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.proto.EventDevProto.internal_static_com_lvl6_proto_DevResponseProto_fieldAccessorTable;
    }
    
    public enum DevStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      SUCCESS(0, 1),
      FAIL_OTHER(1, 2),
      ;
      
      public static final int SUCCESS_VALUE = 1;
      public static final int FAIL_OTHER_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static DevStatus valueOf(int value) {
        switch (value) {
          case 1: return SUCCESS;
          case 2: return FAIL_OTHER;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<DevStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<DevStatus>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DevStatus>() {
              public DevStatus findValueByNumber(int number) {
                return DevStatus.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.lvl6.proto.EventDevProto.DevResponseProto.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final DevStatus[] VALUES = {
        SUCCESS, FAIL_OTHER, 
      };
      
      public static DevStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private DevStatus(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.lvl6.proto.DevResponseProto.DevStatus)
    }
    
    private int bitField0_;
    // optional .com.lvl6.proto.MinimumUserProto sender = 1;
    public static final int SENDER_FIELD_NUMBER = 1;
    private com.lvl6.proto.UserProto.MinimumUserProto sender_;
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.lvl6.proto.UserProto.MinimumUserProto getSender() {
      return sender_;
    }
    public com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder getSenderOrBuilder() {
      return sender_;
    }
    
    // optional .com.lvl6.proto.DevResponseProto.DevStatus status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private com.lvl6.proto.EventDevProto.DevResponseProto.DevStatus status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.lvl6.proto.EventDevProto.DevResponseProto.DevStatus getStatus() {
      return status_;
    }
    
    // optional .com.lvl6.proto.FullUserMonsterProto fump = 3;
    public static final int FUMP_FIELD_NUMBER = 3;
    private com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto fump_;
    public boolean hasFump() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto getFump() {
      return fump_;
    }
    public com.lvl6.proto.MonsterStuffProto.FullUserMonsterProtoOrBuilder getFumpOrBuilder() {
      return fump_;
    }
    
    private void initFields() {
      sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
      status_ = com.lvl6.proto.EventDevProto.DevResponseProto.DevStatus.SUCCESS;
      fump_ = com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, status_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, fump_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, fump_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.proto.EventDevProto.DevResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.EventDevProto.DevResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventDevProto.DevResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.EventDevProto.DevResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventDevProto.DevResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.EventDevProto.DevResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventDevProto.DevResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.EventDevProto.DevResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.EventDevProto.DevResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.EventDevProto.DevResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.proto.EventDevProto.DevResponseProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.proto.EventDevProto.DevResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.proto.EventDevProto.internal_static_com_lvl6_proto_DevResponseProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.proto.EventDevProto.internal_static_com_lvl6_proto_DevResponseProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.proto.EventDevProto.DevResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSenderFieldBuilder();
          getFumpFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (senderBuilder_ == null) {
          sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = com.lvl6.proto.EventDevProto.DevResponseProto.DevStatus.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (fumpBuilder_ == null) {
          fump_ = com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto.getDefaultInstance();
        } else {
          fumpBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.proto.EventDevProto.DevResponseProto.getDescriptor();
      }
      
      public com.lvl6.proto.EventDevProto.DevResponseProto getDefaultInstanceForType() {
        return com.lvl6.proto.EventDevProto.DevResponseProto.getDefaultInstance();
      }
      
      public com.lvl6.proto.EventDevProto.DevResponseProto build() {
        com.lvl6.proto.EventDevProto.DevResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.proto.EventDevProto.DevResponseProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.proto.EventDevProto.DevResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.proto.EventDevProto.DevResponseProto buildPartial() {
        com.lvl6.proto.EventDevProto.DevResponseProto result = new com.lvl6.proto.EventDevProto.DevResponseProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (senderBuilder_ == null) {
          result.sender_ = sender_;
        } else {
          result.sender_ = senderBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (fumpBuilder_ == null) {
          result.fump_ = fump_;
        } else {
          result.fump_ = fumpBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.proto.EventDevProto.DevResponseProto) {
          return mergeFrom((com.lvl6.proto.EventDevProto.DevResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.proto.EventDevProto.DevResponseProto other) {
        if (other == com.lvl6.proto.EventDevProto.DevResponseProto.getDefaultInstance()) return this;
        if (other.hasSender()) {
          mergeSender(other.getSender());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasFump()) {
          mergeFump(other.getFump());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.lvl6.proto.UserProto.MinimumUserProto.Builder subBuilder = com.lvl6.proto.UserProto.MinimumUserProto.newBuilder();
              if (hasSender()) {
                subBuilder.mergeFrom(getSender());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSender(subBuilder.buildPartial());
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.lvl6.proto.EventDevProto.DevResponseProto.DevStatus value = com.lvl6.proto.EventDevProto.DevResponseProto.DevStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                status_ = value;
              }
              break;
            }
            case 26: {
              com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto.Builder subBuilder = com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto.newBuilder();
              if (hasFump()) {
                subBuilder.mergeFrom(getFump());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFump(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .com.lvl6.proto.MinimumUserProto sender = 1;
      private com.lvl6.proto.UserProto.MinimumUserProto sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.proto.UserProto.MinimumUserProto, com.lvl6.proto.UserProto.MinimumUserProto.Builder, com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder> senderBuilder_;
      public boolean hasSender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.lvl6.proto.UserProto.MinimumUserProto getSender() {
        if (senderBuilder_ == null) {
          return sender_;
        } else {
          return senderBuilder_.getMessage();
        }
      }
      public Builder setSender(com.lvl6.proto.UserProto.MinimumUserProto value) {
        if (senderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sender_ = value;
          onChanged();
        } else {
          senderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setSender(
          com.lvl6.proto.UserProto.MinimumUserProto.Builder builderForValue) {
        if (senderBuilder_ == null) {
          sender_ = builderForValue.build();
          onChanged();
        } else {
          senderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeSender(com.lvl6.proto.UserProto.MinimumUserProto value) {
        if (senderBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              sender_ != com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance()) {
            sender_ =
              com.lvl6.proto.UserProto.MinimumUserProto.newBuilder(sender_).mergeFrom(value).buildPartial();
          } else {
            sender_ = value;
          }
          onChanged();
        } else {
          senderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearSender() {
        if (senderBuilder_ == null) {
          sender_ = com.lvl6.proto.UserProto.MinimumUserProto.getDefaultInstance();
          onChanged();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.lvl6.proto.UserProto.MinimumUserProto.Builder getSenderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSenderFieldBuilder().getBuilder();
      }
      public com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder getSenderOrBuilder() {
        if (senderBuilder_ != null) {
          return senderBuilder_.getMessageOrBuilder();
        } else {
          return sender_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.proto.UserProto.MinimumUserProto, com.lvl6.proto.UserProto.MinimumUserProto.Builder, com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder> 
          getSenderFieldBuilder() {
        if (senderBuilder_ == null) {
          senderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.proto.UserProto.MinimumUserProto, com.lvl6.proto.UserProto.MinimumUserProto.Builder, com.lvl6.proto.UserProto.MinimumUserProtoOrBuilder>(
                  sender_,
                  getParentForChildren(),
                  isClean());
          sender_ = null;
        }
        return senderBuilder_;
      }
      
      // optional .com.lvl6.proto.DevResponseProto.DevStatus status = 2;
      private com.lvl6.proto.EventDevProto.DevResponseProto.DevStatus status_ = com.lvl6.proto.EventDevProto.DevResponseProto.DevStatus.SUCCESS;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.lvl6.proto.EventDevProto.DevResponseProto.DevStatus getStatus() {
        return status_;
      }
      public Builder setStatus(com.lvl6.proto.EventDevProto.DevResponseProto.DevStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = com.lvl6.proto.EventDevProto.DevResponseProto.DevStatus.SUCCESS;
        onChanged();
        return this;
      }
      
      // optional .com.lvl6.proto.FullUserMonsterProto fump = 3;
      private com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto fump_ = com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto, com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto.Builder, com.lvl6.proto.MonsterStuffProto.FullUserMonsterProtoOrBuilder> fumpBuilder_;
      public boolean hasFump() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto getFump() {
        if (fumpBuilder_ == null) {
          return fump_;
        } else {
          return fumpBuilder_.getMessage();
        }
      }
      public Builder setFump(com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto value) {
        if (fumpBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fump_ = value;
          onChanged();
        } else {
          fumpBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setFump(
          com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto.Builder builderForValue) {
        if (fumpBuilder_ == null) {
          fump_ = builderForValue.build();
          onChanged();
        } else {
          fumpBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeFump(com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto value) {
        if (fumpBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              fump_ != com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto.getDefaultInstance()) {
            fump_ =
              com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto.newBuilder(fump_).mergeFrom(value).buildPartial();
          } else {
            fump_ = value;
          }
          onChanged();
        } else {
          fumpBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearFump() {
        if (fumpBuilder_ == null) {
          fump_ = com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto.getDefaultInstance();
          onChanged();
        } else {
          fumpBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto.Builder getFumpBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getFumpFieldBuilder().getBuilder();
      }
      public com.lvl6.proto.MonsterStuffProto.FullUserMonsterProtoOrBuilder getFumpOrBuilder() {
        if (fumpBuilder_ != null) {
          return fumpBuilder_.getMessageOrBuilder();
        } else {
          return fump_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto, com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto.Builder, com.lvl6.proto.MonsterStuffProto.FullUserMonsterProtoOrBuilder> 
          getFumpFieldBuilder() {
        if (fumpBuilder_ == null) {
          fumpBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto, com.lvl6.proto.MonsterStuffProto.FullUserMonsterProto.Builder, com.lvl6.proto.MonsterStuffProto.FullUserMonsterProtoOrBuilder>(
                  fump_,
                  getParentForChildren(),
                  isClean());
          fump_ = null;
        }
        return fumpBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.lvl6.proto.DevResponseProto)
    }
    
    static {
      defaultInstance = new DevResponseProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.lvl6.proto.DevResponseProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lvl6_proto_DevRequestProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lvl6_proto_DevRequestProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lvl6_proto_DevResponseProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lvl6_proto_DevResponseProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016EventDev.proto\022\016com.lvl6.proto\032\tDev.pr" +
      "oto\032\022MonsterStuff.proto\032\nUser.proto\"\200\001\n\017" +
      "DevRequestProto\0220\n\006sender\030\001 \001(\0132 .com.lv" +
      "l6.proto.MinimumUserProto\022.\n\ndevRequest\030" +
      "\002 \001(\0162\032.com.lvl6.proto.DevRequest\022\013\n\003num" +
      "\030\003 \001(\005\"\336\001\n\020DevResponseProto\0220\n\006sender\030\001 " +
      "\001(\0132 .com.lvl6.proto.MinimumUserProto\022:\n" +
      "\006status\030\002 \001(\0162*.com.lvl6.proto.DevRespon" +
      "seProto.DevStatus\0222\n\004fump\030\003 \001(\0132$.com.lv" +
      "l6.proto.FullUserMonsterProto\"(\n\tDevStat",
      "us\022\013\n\007SUCCESS\020\001\022\016\n\nFAIL_OTHER\020\002B\017B\rEvent" +
      "DevProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_lvl6_proto_DevRequestProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_lvl6_proto_DevRequestProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_lvl6_proto_DevRequestProto_descriptor,
              new java.lang.String[] { "Sender", "DevRequest", "Num", },
              com.lvl6.proto.EventDevProto.DevRequestProto.class,
              com.lvl6.proto.EventDevProto.DevRequestProto.Builder.class);
          internal_static_com_lvl6_proto_DevResponseProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_lvl6_proto_DevResponseProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_lvl6_proto_DevResponseProto_descriptor,
              new java.lang.String[] { "Sender", "Status", "Fump", },
              com.lvl6.proto.EventDevProto.DevResponseProto.class,
              com.lvl6.proto.EventDevProto.DevResponseProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lvl6.proto.DevProto.getDescriptor(),
          com.lvl6.proto.MonsterStuffProto.getDescriptor(),
          com.lvl6.proto.UserProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
